### ISSUE TITLE
Create Meeting Connector

### ISSUE THREAD

**Issue by kakasoo** [wrtnio/connectors#11]
# requirements
- Creates a new Zoom Meeting. (Options not available here will default to user/account Zoom settings.)

# API Spec

```
POST {{baseUrl}}/users/:userId/meetings
```
- `userId` : (Required) The user's user ID or email address. For user-level apps, pass the `me` value.

**Comment by kakasoo** [comment]
# API Spec

- https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate

**Comment by kakasoo** [comment]
# Question
- Scopes: meeting:write:admin,meeting:write
- Granular Scopes: meeting:write:meeting,meeting:write:meeting:admin

세분화된 스코프가 존재하는 경우 어떻게 전달해야 하는지?

**Comment by samchon** [comment]
@seunghwako 어떻게 해야하나요?

**Comment by seunghwako** [comment]
@kakasoo 만약 구글처럼 세분화된 scope들이 존재하고 세분화된 scope들을 모두 포함하는 scope이 존재한다면 fe쪽에서 현재는 판단하기 어려운 구조입니다. zoom에도 그런 scope들이 존재하나요? cc @kimulchan

이와는 별도로 scope들이 필요한 커넥터가 있을 경우 노션 페이지에 정리해주시면 됩니다.

노션 페이지: https://www.notion.so/wrtn/Scope-list-00a0edbb2c1f40548dfd6dc58a81e401

**Comment by kakasoo** [comment]
@seunghwako 

> @kakasoo 만약 구글처럼 세분화된 scope들이 존재하고 세분화된 scope들을 모두 포함하는 scope이 존재한다면 fe쪽에서 현재는 판단하기 어려운 구조입니다. zoom에도 그런 scope들이 존재하나요? cc @kimulchan
> 
> 이와는 별도로 scope들이 필요한 커넥터가 있을 경우 노션 페이지에 정리해주시면 됩니다.
> 
> 노션 페이지: https://www.notion.so/wrtn/Scope-list-00a0edbb2c1f40548dfd6dc58a81e401

확인했습니다.
문서 상에 있는 거 확인하긴 했는데요, 일단 우리가 사용하는 커넥터 별로 어떻게 상이한지 몰라서 포함관계인지 아니면 텍스트만 보고 구분할 수 없는건지도 아직 파악이 안됩니다.
발견하는대로 공유 주신 문서에 기록하겠습니다.

**Comment by kakasoo** [comment]
이 Connector의 경우 scope가 1개기 때문에 크게 신경 쓸 필요 없었던 거 같습니다.
다른 Connector들도 연동한 다음 scope에 또 다른 우려사항이 있을 때 다시 논의하면 될 거 같습니다. 일단 문서에는 1개지만 기입해두었습니다.
