### ISSUE TITLE
디스코드 이슈

### ISSUE THREAD

**Issue by hakjje** [wrtnio/connectors#40]
Find User By Email | 이메일 주소를 통해 사용자를 찾고자 합니다.이 엔드포인트를 호출하여 이메일 주소를 통해 사용자를 검색할 수 있습니다.
ㄴ Discord API는 이메일 주소를 통한 사용자 검색 기능을 제공하지 않습니다.

Find User by ID | ID로 사용자를 찾는 엔드포인트를 사용합니다.이 엔드포인트를 호출하여 사용자 ID를 통해 사용자를 검색할 수 있습니다. 검색 결과로 특정 id의 리스트가 나옵니다.
ㄴID 라는게 흔히 사용하는 hakjje 라는 ID가 맞을까요? ID 를 사용하는 api 의 경우 123456789012345678 처럼 사용자의 pk 개념의 123456789012345678 로 api 연동이 가능합니다.

어떻게 진행하면 될까요? 답변 부탁드립니다.

**Comment by kakasoo** [comment]
# Find User By Email Issue
그렇다면 채널을 조회하는 API로 대체 부탁드립니다.

# Find User By ID
말씀하신대로 ID 값을 이용해 유저를 조회하는 흐름으로 작업해주시면 되겠습니다.

cc. @samchon
